### ISSUE TITLE
[NPC'S] Hungering Wraith - Wailing Death

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#103]
**Name der Quest/Item/Object/etc**
[NPC'S] Gahrron's Withering - Hungering Wraith - Wailing Death
**Was Funktoniert nicht?**
genannte Mobs sind nicht elite
**Wie sollte es Funktonieren**
benannte Mobs müssten eigentlich alle Elite sein
**Screenshot/Video**
http://db.vanillagaming.org/?npc=1802
http://db.vanillagaming.org/?npc=1804

**Comment by Elmo337** [comment]
http://vanilla-wow.pro/datenbank/aowow/?npc=1802
 und in jeglichen anderen Datenbank sind sie normal

**Comment by GitHubNoa** [comment]
ok, dann close pls!
