### ISSUE TITLE
Quest: Wandering Shay

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#106]
http://db.vanillagaming.org/?quest=2845
Die Quest geht zwar, aber der NPC Shay Leafrunner sagt immer "error"  zw. kleiner und größer Zeichen

**Comment by GitHubNoa** [comment]
ich glaube du hast den Satz nicht zu Ende geschrieben oder`?

**Comment by Nathaliana** [comment]
eigentlich schon, aber er nimmt die brackets nicht
