### ISSUE TITLE
BRT-Arena

### ISSUE THREAD

**Issue by Skipthis** [Elmo337/Vanilla-WoW-Project#11]
Leider funktioniert das BRT-Arena-Event nicht richtig.
Es sollten nach Beginn 2 Gegnergruppen die Arena betreten.
Die Gruppen erscheinen kurz am Eingang und nehmen dann einen anderen Weg.
Wenn man verpasst die zweite Gruppe oder auch nur einen Gegner herauszuziehen, ist diese bzw.
dieser nicht in dem Gang zu finden und das Event kann nicht fortgesetzt werden.

**Comment by Elmo337** [comment]
Hi, die vicher laufen ja wirklich durch die Wand 🗡

Ich habs jetzt so gelöst das ich denen einen Wegpunkt gegeben hab sowohl den Mobs als auch den Bossen. Hoffentlich klappt das damit.

**Comment by Elmo337** [comment]
Leider hat meine Variante nicht Funktoniert aber ich hab den Fehler gefunden ! Ist ein Core Fehler. Sollte  in 1-2 Tagen fertig sein

**Comment by Skipthis** [comment]
Ich frag mich immer noch was das für ein Pfad ist?
Die laufen in der Decke quer durch den Folterbereich, vorbei an der Verhörmeisterin und
verschwinden dann ...

**Comment by Elmo337** [comment]
Das problem liegt an einer Zeile weil die "Arena" eine Mitte zugeteilt wurde "SetArenaCenter" und dieser wurde ausgeklammert ich hab das wohl gefixt und diesen wieder eingeklammert hat aber eine Compile Error verursacht, diesen musste ich dann auch wieder beheben 

Das fertige Produkt sieht dann so aus
https://github.com/mangos/ScriptDev3/commit/5f4ed0747b170e98108a0a080c5936442ec2e0ba

**Comment by Skipthis** [comment]
Es ist zwar schon etwas her, daß ich das letzte Mal reingesehen habe, aber als ich die NPC`s auf ihrem
Weg etwas "geärgert" habe, sind diese ordnungsgemäß resettet und im Gang verblieben.
Daher denke ich das sie grundsätzlich richtig funktionieren.
Evtl. sollte man das mit dem Wegpunkt nochmal versuchen.
