### ISSUE TITLE
Quest: Mazzranach

### ISSUE THREAD

**Issue by Drudimix** [Elmo337/Vanilla-WoW-Project#110]
**Name der Quest** Mazzranach (Mulgore tauren gebiet)

**Was Funktoniert nicht?** es droppt der knochen des flachlandpumas nicht

**Wie sollte es Funktonieren** der knochen solte droppen (droppchonce classis stand 80%)

**Screenshot/Video** ich weis nicht wie ich davon nen screen machen soll^^

MFG

**Comment by Elmo337** [comment]
http://vanilla-wow.pro/datenbank/aowow/?item=4805 Das Item dropt auch der Flachlandpuma und nicht der Mazzranach ;)

**Comment by Drudimix** [comment]
die quest heist so und das item soll bei den pumas droppen ja aber die pumas droppen es nicht
