### ISSUE TITLE
Blasted Lands - Steine der Bindung

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#112]
Steine der Bindung sind nicht anklickbar für Spieler. Werden benötigt, um die Diener zu töten, da diese sonst ab ca. 1% Leben, jeglichen Schaden absorbieren. Oder sind die nur anklickbar, wenn man die Quest hat?

**Comment by Elmo337** [comment]
> Oder sind die nur anklickbar, wenn man die Quest hat?

Genau so ist es
