### ISSUE TITLE
Fehler beim Kampf gegen die Baroness Anastari

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#118]
Wenn man bei der Übernahme von seiner Gruppe umgebracht wird (danke an die Beteiligten ;-P ), und in diesem Moment die Baroness einen wieder freigibt, hat man die Meldung, daß man gestorben ist (mit allem drum und dran wie: HP, MP wieder so halb hoch, marterielle Form), allerdings kann man nichts machen, da man dennoch "tot" ist.
Funktionieren tut nicht: 
Alt+F4 mit relog,
sich neu einloggen mit 2. Client,
Beenden des Spiels über Exit und Relogin
aus der Instanz laufen und wieder rein laufen (Meldung, man kann als Geist nicht in die Ini)
aus der Instanz zu Geistheiler laufen zur Wiederbelebung (keine Option vorhanden)

Irgendwann bin ich dann allerdings draußen vor dem Geistheiler "richtig" gestorben ? Sollte eigentlich in der Instanz sein !?

Vermutung: beim Sterben durch die Teammitglieder wurde der "Übernahme-Debuff" der Baroness nicht oder nicht richtig entfernt. Dieser bleibt afaik einige Minuten erhalten, bis er verschwindet, und man erst dann "normal" sterben kann. Keine Ahnung, aber ansonsten habe ich keine Idee hierzu.
GM Commands wie Char töten oder wiederbeleben konnte ich leider nicht testen (commands aus anderem Level ;) )

**Comment by SailorSat** [comment]
Kann ich bestätigen.

Alt-F4 hilft schon, allerdings muss man mehrere Minuten warten bis der Char auch wirklich "aus der Spielwelt" verschwindet.
