### ISSUE TITLE
Umlaute und Übersetzungen

### ISSUE THREAD

**Issue by Agorass** [Elmo337/Vanilla-WoW-Project#119]
**Name der Quest/Item/Object/etc**    Siehe Titel

**Was Funktoniert nicht?**   Viele Texte sind noch Englisch und Umlaute sind nicht verfügbar und werden durch ein "?" ersetzt.

**Wie sollte es Funktonieren**  Umlaute " ä ö ü ß " sollten angezeigt werden, und Texte sollten Deutsch sein.

**Comment by SailorSat** [comment]
Habe im Prinzip alle Umlaute korrigiert.
Allerdings fehlen noch unmengen an deutschen Texten.
