### ISSUE TITLE
Dunkelmond - Jahrmarkt / Goldhain

### ISSUE THREAD

**Issue by Agorass** [Elmo337/Vanilla-WoW-Project#120]
**Name der Quest/Item/Object/etc**             Dunkelmond - Jahrmarkt / Goldhain

**Wie sollte es Funktonieren**                       Dunkelmond - Jahrmarkt sollte nur zu bestimmten Zeiten                                 aufgebaut sein und nicht dauerhaft.

**Screenshot/Video**

**Comment by SailorSat** [comment]
Über welchen Zeitraum hast du diese Feststellung gemacht?

Aktuell ist nämlich kein Dunkelmond Jahrmarkt aufgebaut - Weder in Goldshire noch in Mulgore.

**Comment by Agorass** [comment]
2 Tage bevor ich das issue eröffnet habe. Habe auch schon gesehen dass er wieder weg ist.
hmmm vtl. stimmt was mit der Zeiteinstellung nicht.. Ist aber nicht weiter tragisch.
thx für den Repost ;D
