### ISSUE TITLE
Geistheiler Fehler

### ISSUE THREAD

**Issue by Agorass** [Elmo337/Vanilla-WoW-Project#121]
**Name der Quest/Item/Object/etc** Geistheiler

**Was Funktoniert nicht?**  Text ist in Englisch und die Option sich bei ihm rezzen zu lassen, steht in Befehlszeile da.

**Wie sollte es Funktonieren**
Text sollte in Deutsch sein, und die Befehlszeile sollte anders sein.

**Screenshot/Video**
![wowscrnshot_100717_211920](https://user-images.githubusercontent.com/13293569/31311124-d50bcd8a-aba5-11e7-86db-165bf8b90c3f.png)
](url)

**Comment by SailorSat** [comment]
Ich habe ein paar NPCs diesbezüglich korrigiert.
Problem ist hier primär das teilweise sogar im englischen Client nur "GOSSIP_OPTIONS" stehen.

Englische NPC Texte sind in Arbeit.
