### ISSUE TITLE
bug mit der bär gestallt vom druiden

### ISSUE THREAD

**Issue by Drudimix** [Elmo337/Vanilla-WoW-Project#122]
**Name der Quest/Item/Object/etc** quest geber etc. algemein npc´s

**Was Funktoniert nicht?** ich habe soeben meine bär q reihe abgeschlossen und in der bärengestallt kann man mit keinem npc interargieren(lehrer,questgeber etc. (habe nicht jeden npc getestet))

**Wie sollte es Funktonieren** man solte in der gestallt mit quest geber etc. redenkönnen sowie quest annhemen können

wo: donnerfels-> anhöhe der Ältesten->(beispiel npc druidenlehrer: Turak Runentotem)

**Comment by SailorSat** [comment]
Ist normal. In Gestaltform kann man überhaupt nicht interagieren. Gängige AddOns, etwa AutoMate gehen automatisch aus der Gestalt raus sofern man mit jemand/etwas interagieren möchte.
