### ISSUE TITLE
Verderbte Säbler

### ISSUE THREAD

**Issue by Juljin** [Elmo337/Vanilla-WoW-Project#125]
**Name der Quest/Item/Object/etc**
Verderbte Säbler
**Was Funktoniert nicht?**
Die veränderte Katze kann man nicht zurückbringen.
**Wie sollte es Funktonieren**
Man sollte die Katze bei der Questgeberin zurückbringen können die reagiert aber nicht.
**Screenshot/Video**

**Comment by SailorSat** [comment]
Verändert sich die Katze denn wenn du sie am Mondbrunnen frei lässt?

**Comment by SailorSat** [comment]
Kann ich bestätigen - Stehe mit dem Corrupted Saber neben dem NPC und nichts passiert.

**Comment by SailorSat** [comment]
Nach genauem Lesen der Quest... Katze ansprechen und frei lassen :)
