### ISSUE TITLE
Schamanen Totem

### ISSUE THREAD

**Issue by Skipthis** [Elmo337/Vanilla-WoW-Project#13]
Das Totem der Krankheitsreinigung und das Totem der Giftreinigung entfernen
die jeweiligen Effekte  nicht.

**Comment by Elmo337** [comment]
Stimmt ein bekannter Fehler von Mangos, ich versuch den Effekt auf das Totem per DB zu setzen, gucken wir mal obs was bringt ^^

Liebe Grüße

**Comment by Elmo337** [comment]
Habs jetzt nochmal anders versucht zu Lösen, nach dem Restart werden wir sehen obs geklappt hat 👍

**Comment by Zugu-Azshara** [comment]
Hey, gibt's eigentlich schon ne Lösung bezüglich der  beiden Totems ? LG
