### ISSUE TITLE
Die oberste Beschützerin

### ISSUE THREAD

**Issue by xAhDaZx** [Elmo337/Vanilla-WoW-Project#15]
Die oberste Beschützerin

Die Schuppe hat keine Usefunktion und wenn man auf der Rune steht/springt/sitzt passiert nichts.

Lange her... weiß ich nicht genau...
evtl. hilft dir das:
http://wowdata.buffed.de/quest/Schwarzfelsspitze/Die-oberste-Beschuetzerin-5160

**Comment by Elmo337** [comment]
Sollte nach dem Server Restart funktionieren !
