### ISSUE TITLE
Waldeslied / Eschental

### ISSUE THREAD

**Issue by Aecletec** [Elmo337/Vanilla-WoW-Project#19]
WALDESLIED / ESCHENTAL FEHLT
**Illiyana**;**Schildwache Melyria Frostschatten**

**gesamtes Lager bis auf einen NPC (Kayneth Stillwind) fehlt.**

**es sollten verschiedene NPC´s dort sein, namentlich mindestens: Schildwache Melyria Frostschatten & Illiyana (bei denen man auch Quests abgeben kann die man im Moment auch annhemen kann, spirch diese NPCs sollten zum jetzigen Stand des Spiels auf jeden Fall integriert sein. Ich glaube es gab da auch sogar einen Flugpunkt, da bin ich mir aber nicht mehr sicher. **

**Comment by spreizhose** [comment]
Das Problem mit Waldeslied ist, dass NPC wie Schildwache Melyria Frostschatten zwar auf dem Patchstand bereits existieren aber noch nicht in Waldeslied sondern am Schrein von Aesina stehen (Wird glaube ich so geschrieben). Es stimmt lediglih die Info im Questtext nicht, da dieser aus der Datenbank von TBC entnommen ist. Der Flugpunkt in Waldeslied war zu Classic noch nicht vorhanden.
