### ISSUE TITLE
Katzengestalt/Bärengestalt tooltip

### ISSUE THREAD

**Issue by Aecletec** [Elmo337/Vanilla-WoW-Project#20]
**Katzengestalt,Bärengestalt**

**der Tooltip der Fähigkeiten zeigt nur den Bonus (ap&HP bei Bär, und ap bei Katze) von lvl 10 bzw 20 an**

**sollte mit jedem lvl ansteigen (die Werte steigen mit jedem lvl auch an,auch die Auren der Fähigkeiten, also der "Buff" wenn man verwandelt ist, zeigt die richtigen Werten. Nur der Zauber selbst in der Leiste und im Buch nicht. ist eine Kleinigkeit aber dennoch ein Bug.

**Comment by Elmo337** [comment]
Den fehler hab ich z.b nicht, einfach mal den WDB Ordner Löschen

LG
