### ISSUE TITLE
Npc mit zu viel hit!

### ISSUE THREAD

**Issue by Thooms92** [Elmo337/Vanilla-WoW-Project#21]
Name der Quest:

Körper und Herz

Was Funktoniert nicht?:

Der Gegner "Mondklaue" haut einmal auf einen drauf und man ist tod... ( Als lvl 10er Druide )

Wie sollte es Funktonieren:

Ein ausgewogener Kampf in dem man Mondklaue besiegt.

Screenshot/Video

**Comment by Skipthis** [comment]
Einfach gaaanz entspannt "totwurzeln" ^^
