### ISSUE TITLE
Paladin: Weihe

### ISSUE THREAD

**Issue by Chlothar** [Elmo337/Vanilla-WoW-Project#22]
Zauber: Weihe ID:26573 http://db.vanillagaming.org/?spell=26573

Der Zauber skaliert nicht mit dem Stärke-Wert des Paladins, was die Zaubermacht angeht habe ich nicht das nötige gear es zu testen. Weihe tickt nur den basisschaden, z.B.: 8dmg pro tick auf rang 1, unabhängig davon wieviel stärke ich habe.

Weihe sollte eigentlich mit der Stärke und Zaubermacht des Paladin skalieren. "Consecrates the land beneath the Paladin, doing [8 * (X + 0.04 * SPH + 0.04 * AP)] Holy damage over 8 sec to enemies who enter the area."  http://vanilla-wow.wikia.com/wiki/Consecration

**Screenshot/Video**

**Comment by Skipthis** [comment]
Wahrscheinlich irre ich mich, aber wenn ich mich richtig erinnere war die einzige Möglichkeit Einfluß über 
das Equipment auf den Zauberschaden zu nehmen die Zaubermacht.
Sonst hätte sich der Wert ja schon beim leveln ändern müssen, bevor man entsprechendes Equip hat und 
das hat er nicht.

**Comment by spreizhose** [comment]
Tatsächlich sollte es sich so verhalten, wie ich es geschildert habe. Der Schadenszuwachs über Stärke und Zaubermacht ist wenig spürbar, da der Gesamtschaden über 8 ticks verteilt wird, sollte aber dennoch und bereits während des Levelns vorhanden seit, wenn auch das gear im Levelbereich sich nur marginal auswirkt.

**Comment by spreizhose** [comment]
Habe zur Berechnung noch folgendes gefunden http://cmangos.net/thread-6605.html
