### ISSUE TITLE
Paladin Richturteil der Gerechtigkeit

### ISSUE THREAD

**Issue by Skipthis** [Elmo337/Vanilla-WoW-Project#23]
Das Richturteil der Gerechtigkeit sollte verhindern, daß NPC flüchten.
Die Anzeige lautet auch richtig "Kann nicht fliehen".
Leider laufen sie dann doch mit dem aufliegenden Richturteil davon.

Ist nicht ganz so dramatisch, weil man ja durch entsprechenden Pull vorbeugen kann bevor sie
adden.

**Comment by Elmo337** [comment]
Das gleiche Problem hat der Hexenmeister mit seinem Stun, manchmal laufen sie noch nen Meter weiter bleiben aber dann stehen komisch, kümmere mich drum
