### ISSUE TITLE
 Paladin: Auslösen des Zaubers "Rache" bei Waffenproccs/Richturteilen

### ISSUE THREAD

**Issue by Chlothar** [Elmo337/Vanilla-WoW-Project#24]
Zauber "Rache" - Vengeance ID#20049 http://db.vanillagaming.org/?spell=20049

Rache wird bei kritischen Richurteilen///kritischen Waffenprocs/// kritischen Offhand procs nicht ausgelöst, sollte es aber. Wie z.B. Kritischen "Richturteil des Befehls" (Judgement of command ID#20452 http://db.vanillagaming.org/?spell=20425)

Sämtliche kritischen Schadenseffekte sollten "Rache" auslösen, diese gewährt für 8 Sekunden einen Schadensbonus je nach rang# 3-15%.

**Comment by Elmo337** [comment]
Speziell jetzt nur Rang 1 oder bei alllen?
