### ISSUE TITLE
Allgemeines Fluchtverhalten

### ISSUE THREAD

**Issue by Skipthis** [Elmo337/Vanilla-WoW-Project#25]
Mir ist aufgefallen, daß flüchtende NPC´s nicht aufgehalten werden können.
Man sollte daher einen entsprechenden Verlangsamungseffekt wirken bevor diese flüchten.
Bereits flüchtende NPC´s können nicht zur Umkehr bewegt werden (Fluch oder Richturteil).
Auch können diese nicht durch entsprechende Effekte benommen oder betäubt werden.

**Comment by Elmo337** [comment]
Ist mir gestern auch schon aufgefallen das MANCHE Flüchtende NPCs nicht Festgehalten werden. Manchmal klappts manchmal nicht
