### ISSUE TITLE
Quest: Untersuchungen im Blauen Eremiten

### ISSUE THREAD

**Issue by knoeddelchen** [Elmo337/Vanilla-WoW-Project#33]
Hallo!

Questname: Untersuchungen im Blauen Eremiten (Magier-Quest)

Wenn der Questgegenstand "Inkanation der Manifestion" genutzt wird spornen keine Mobs. 

Eigentlich sollte mit Benutzung des Gegenstands "Geister" gespornt werden, die man anschließend in die Truhe mit Verwahrungskästchen in diese einschließt. Für die Quest müssen 3 Geister gefangen werden.

Lg,
Knöddelchen

**Comment by Kampfkrapfn** [comment]
Kann ich so bestätigen, Questmobs spawnen nicht. Auch ein Tipp seitens anderer PServer, dass man die Geister per AoE-Attacken angreifen könnte, trifft bei uns nicht zu - genauso wie ein weiterer Tipp, dass die Questmobs am Brunnen in SW spawnen würden.
