### ISSUE TITLE
Quest: Verseuchtes Land

### ISSUE THREAD

**Issue by Gogiwolf** [Elmo337/Vanilla-WoW-Project#34]
Quest: Verseuchtes Land.

Wenn man die Laufe auslegt, erscheint diese zwar auf dem Boden, der angelockte Tollwütige Distelbär wird aber nicht zahm.

Wenn ein "Tollwütiger Distelbär" in die Falle läuft, wird er freundlich und folgt einem bis zum Questgeber in Auberdine.

**Comment by Chlothar** [comment]
Also ich habe die Quest mehrfach getestet, Sie ist machbar, man muss den Bären nur ein wenig umpositionieren während des Kampfes und auf etwa 60% seines Lebens bringen.

**Comment by Gogiwolf** [comment]
Hallo Chlothar, danke für die Tips. Beim dritten Anlauf hat es jetzt geklappt. Man muss wirklich ein wenig spazieren gehen, sprich den Bären immer wieder aus einem anderen Richtung über die Falle ziehen. Ist also erledigt.
