### ISSUE TITLE
Quest: Geschäftsbuch aus Tanaris

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#38]
**Name der Quest/Item/Object/etc**
Geschäftsbuch aus Tanaris
**Was Funktoniert nicht?**
Das Questitem "Goldstahls Geschäftsbuch" wird nicht generiert
**Wie sollte es Funktonieren**
Nach Ansprechen des Plumpsklos und anschließendem Betätigen der Gesprächsoption sollte neben dem Klohäuschen ein Container auftauchen, aus dem man das Geschäftsbuch looten kann.
**Screenshot/Video**

**Comment by Chlothar** [comment]
Kann ich nicht bestätigen, habe die Quest mehrfach abgeschlossen.
