### ISSUE TITLE
Quest: Fragments of the Past

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#43]
**Name der Quest/Item/Object/etc**
Fragmente der Vergangenheit / Fragments of the Past
http://db.vanillagaming.org/?quest=5247
**Was Funktoniert nicht?**
Die zu füllende Phiole lässt sich nicht füllen
**Wie sollte es Funktonieren**
Steht man an der Vogeltränke und benutzt die Phiole, so sollte sie als gefüllte Phiole im Inventar auftauchen
**Screenshot/Video**

**Comment by Chlothar** [comment]
Ja, den bug hatte ich schon mal gemeldet, scheinbar wurde auch daran gearbeitet, denn der Düsterteich  steht jetzt woanders bzw ist 2x vorhanden, aber funktioniert immer noch nicht.
