### ISSUE TITLE
Drops des Defias-Set

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#45]
**Name der Quest/Item/Object/etc**
Alle Items des Defias-Set
**Was Funktoniert nicht?**
In den Deadmines (und dem Gebiet drumherum) kommt es zu nahezu keinem Drop der BoE-Setteile, stattdessen werden die Teile wie andere grüne Drops behandelt und kommen z.B. in Darkshore vor.
**Wie sollte es Funktonieren**
Die Drop-Location sollte sich auf die Deadmines und das umliegende Gebiet, namentlich alle Defias-Mobs in Westfall beschränken, dort jedoch mit deutlich höheren Dropraten. (~1 BoE Teil je DM-Run)
**Screenshot/Video**

**Comment by Chlothar** [comment]
Dasselbe gilt auch für andere grüne Setteile wie z.B. jene aus HDW.
