### ISSUE TITLE
Falsches Questlevel

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#46]
**Name der Quest/Item/Object/etc**
The Hunter's Path
**Was Funktoniert nicht?**
Quest ist erst ab Lv.10 verfügbar
**Wie sollte es Funktonieren**
Es sollte ab Lv.4 verfügbar sein, vgl. mit der äquivalenten Priesterquest "In Favor of the Light". Beide Quests haben denselben Laufweg und die Belohnung ist bei beiden 100 XP.
**Screenshot/Video**

**Comment by Elmo337** [comment]
Die Hunterquest war schon immer ab Level 10

**Comment by GitHubNoa** [comment]
Jo das war immer Level 10, stimmt.
