### ISSUE TITLE
Gizeltons Karawane (Desolace)

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#50]
**Name der Quest/Item/Object/etc**
Gizeltons Karawane (Questgeber: Rigger Gizelton, [41,80] )
**Was Funktoniert nicht?**
Die Quest funktioniert einmwandfrei aber im Chat wird nach Beenden der Quest weiterhin auf die Quest verwiesen durch Schreien des Questgebers. Es ist eigentlich kein richtiger Bug, aber wenn man in Desolace questet spamt die ganze Zeit der Chat voll. 
**Wie sollte es Funktonieren**
Für Spieler, die die Quests (es sind 2 Karawanenquests) angeschlossen haben, sollte diese Meldung eigentlich nicht mehr im Chat erscheinen. 
**Screenshot/Video**
![screen](https://user-images.githubusercontent.com/29354568/27012612-348398a4-4ed3-11e7-840d-df829ce773b0.jpg)

**Comment by Elmo337** [comment]
Ich hab die Quest mit allen Chars auf dem Test Server gemacht und dort hat er's nur 1x geschrieben

**Comment by Kampfkrapfn** [comment]
ich stehe gerade seit geschlagenen 45 minuten zusammen mit der karawane am südlichen quest-startpunkt und warte darauf, dass die karawane loszieht.
beim ersten mal, ein paar stunden vorher, hatte ich die quest angenommen und schwupps ging es los. quest erfolgreich beendet, karawane vom mittleren lager noch nach norden begleitet. danach habe ich Rigger Gizelton EINMAL die aufforderung für die nördliche quest rufen hören, bin dann aber zu spät dort angekommen. seitdem immer nur rufe aus dem süden.

afaik sollte der rufer 1x schreien, und dann ca drei minuten später die karawane losziehen. dass sie niemals oben ankommt liegt vermutlich daran, dass npcs nur dann berechnet werden, solange sich ein spieler in der nähe aufhält. eine änderung zu "npcs werden berechnet, solange ein spieler im gebiet ist" könnte hier abhilfe schaffen
