### ISSUE TITLE
irreführende Jägerquest

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#52]
**Name der Quest/Item/Object/etc**
"The Path of the Hunter"
**Was Funktoniert nicht?**
Man wird vom Jägerlehrer in IF zum Jägerlehrer in Dolanaar geschickt, um die Zähmquest zu erledigen, die man bereits in Kharanos abgeschlossen hat. Kommt man dort an und will die Folgequest annehmen, so heißt es "Nix da, das ist eine Quest nur für Nachtelfen"
**Wie sollte es Funktonieren**
Man sollte die nach Dolanaar führende Quest gar nicht erst angeboten bekommen.
**Screenshot/Video**

**Comment by Kampfkrapfn** [comment]
Und kommt jetzt blos keiner mit "Das war schon immer so" !
Wir haben hier die einmalige Möglichkeit, etwas BESSER zu machen, als es im Original war!
=> Flüssigeres Spielerlebnis => Mehr Spieler

**Comment by GitHubNoa** [comment]
Recht hast du :)

**Comment by Elmo337** [comment]
Meinst du diese Quest: http://db.vanillagaming.org/?quest=6073 ?
