### ISSUE TITLE
Questabschluß: Meet at the Grave

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#64]
Meet at the Grave / A Grave Situation: wenn man mit dem Geist redet (Quest beendet) steht im Text, daß es XP gibt....gibt aber keine (Expierence gained: 14500 - ist dem 2x geschuldet; nicht wundern) XP Gain kann man ja im Chat-Fenster als extra Anzeige aktivieren...da kommt/ kam nichts.

**Comment by Elmo337** [comment]
Die Quest geben Ingesamt (also die 2 die du genannt hast) 1450 und x2 2900

**Comment by Nathaliana** [comment]
Mag ja sein, aber dann stimmt was nicht bei der Textausgabe... Wenn du die Option XP Gain anhast, bekommst sowohl bei Questabschluß als normalen Text die erhaltenen XP angezeigt als auch als "Statusmeldung" dieselbe XP-Menge...hier gab es beim Abschließen beim Geist (vor der Followup-Quest) allerdings nur die Textmeldung und keine XP-Gain Meldung (die auch die XP letztendlich dem Char zuschreibt). Also ist entweder die Textmeldung falsch, oder es werden fälschlicherweise keine XP dem Char gutgeschrieben. Vielleicht kann man auch als Ghost keine XP bekommen, keine Ahnung.

**Comment by Nathaliana** [comment]
Also das Problem besteht immer noch. Ich hatte 98% auf Level 55 zu 56. Nach Abgabe bei dem Geist kommt eine Meldung, daß ich 14500xp bekommen habe. Nichts passiert, immer noch 98%. Nach dem Wiederbeleben und Abgabe der Quest beim Grabstein 7500xp bekommen, levelup 2% auf Level 56. Zu Linken geflogen, Quest abgegeben 14500xp, 10% auf Level 56...also irgendwie stimmt da immer noch was nicht!
