### ISSUE TITLE
Bags

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#65]
In Mangos war es möglich, eine z.B. 12er Tasche durch eine 14er Tasche zu tauschen, indem man die 14er über die 12er zog (die 14er durfte aber nicht in einem Slot dieser 12er sein). Aktuell geht das nicht...man muß die Tasche, die ersetzt werden soll, leer machen.

**Comment by Elmo337** [comment]
Das ist allerdings erstaunlicherweise richtig so
