### ISSUE TITLE
Stichwort: Umskillkosten

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#66]
Hattest geschrieben, du müßtest das neu compilieren dafür. Vllt. erweiterst du das dahingehend, daß du es als Command ingame setzten kannst....könnte Arbeit sparen.

**Comment by NolinNostralia** [comment]
[Gibt doch schon eine config hierfür..](https://github.com/elysium-project/server/commit/48bd26d98bdfde7ec215a136087b8bbc09e1da32)

**Comment by Elmo337** [comment]
Ich weiß Nolin , hab ich nurnoch nicht eingestellt 

LG
