### ISSUE TITLE
Questitemdrop Twilight Tablet Fragment

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#68]
Werden100%ig gedroppt von Dust Stormers und Whirling Invaders.
Oder ist das nur der Ele-Invasion geschuldet?

**Comment by Kampfkrapfn** [comment]
Sowohl die Elementarinvasion als auch die Twilight-Tablets sollte es in unserem nominellen Patchstand 1.2 nicht geben
