### ISSUE TITLE
Eulen: Klassifizierung fehlt

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#70]
**Name der Quest/Item/Object/etc**
Strigid Hunter (Level 8/9)
**Was Funktoniert nicht?**
Die "Strigid Hunter" Eulen auf Teldrassil sind nicht als "Wildtier" klassifiziert.
**Wie sollte es Funktonieren**
Sie sollten der Klasse "Wildtier" angehören
**Screenshot/Video**
![image](https://user-images.githubusercontent.com/27807765/27113071-10e799e2-50bb-11e7-98eb-a62c521d5854.png)

**Comment by Elmo337** [comment]
Ist bei mir als Wildtier eingetragen
