### ISSUE TITLE
! WICHTIG! Keine Fischschwärme

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#72]
**Name der Quest/Item/Object/etc**
Fischschwärme
**Was Funktoniert nicht?**
ES GIBT KEINE FISCHSCHWÄRME
**Wie sollte es Funktonieren**
ES SOLLTE FISCHSCHWÄRME GEBEN!
**Screenshot/Video**

**Comment by Elmo337** [comment]
Kommt  nächsten Patch
