### ISSUE TITLE
NPC: Commander Ashlam Valorfist

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#73]
Der Typ ist aggressiv eingestellt, als einziger NPC in dem Camp. Bissel doof wenn direkt daneben Argent Dawn Questgeber stehn. Alle anderen NPCs sind dort zwar auch "rot", greifen aber nicht an.

**Comment by Elmo337** [comment]
http://db.vanillagaming.org/?npc=10838 soll zu horde hin feindlich sein
