### ISSUE TITLE
Zul'Farak Event

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#77]
**Name der Quest/Item/Object/etc**
Zul'Farak Event
**Was Funktoniert nicht?**
1. Bevor das Event aktiviert ist, stehen vor der Treppe bereits haufenweise Mobs, man kann die Treppe nicht hoch, ohne alles zu Pullen. 
2. Nachdem man Den Executer killt, und mit dem Schlüssel die Käfige aufschließt, kommen die Mobwaves von unten hoch, allerdings viel zu viele, und viel zu schnell.
**Wie sollte es Funktonieren**
Es sollten vor der Treppe keine die zum event gehören. Diese sollten erst spawnen nachdem das Event aktiviert wurde. Die mobwellen kommen in "langsamen" Abständen nach oben gelaufen und nicht alle auf einmal. 
**Screenshot/Video**

**Comment by Nathaliana** [comment]
Kann ich auch so bestätigen...kamen da an...riesige Meute stand schon unten. Wir haben die dann umgehauen, als dann die ganze Menge einen Respawn erfahren hat - was zum Wipe führte. Im Anschluß sind wir an denen vorbei nach oben, um den Key vom Executioner zu holen. Das ging soweit so gut, aber die Intervalle waren viel zu kurz und irgendwann standen dann praktisch alle Mobs oben.

**Comment by SailorSat** [comment]
Beobachtung: Das Event funktioniert genau ein mal nach Server neustart
