### ISSUE TITLE
Chest Respawntimer

### ISSUE THREAD

**Issue by Queeb** [Elmo337/Vanilla-WoW-Project#78]
**Name der Quest/Item/Object/etc**

Robuste Truhe, vermutlich alle Truhen.

**Was Funktoniert nicht?**

Diverse Respawn Timer für die Robuste Truhe / Solid Chest sind auf 60min anstatt auf ihren eigentlich gesetzten Spawn Zeiten. Dies ist z.B. in Azshara der Fall, wo der Respawn eigentlich nur 3 min ist und in den Sümpfen des Elends, wo der Respawn eigentlich 10/15min ist.

**Wie sollte es Funktonieren**

Die richtigen Vanilla Respawn Zeiten sind nicht alle 60min und pro Gebiet etwas diverser.

Genaue Respawnzeiten für alle Truhen sind in folgender Datenbank hinterlegt:
http://db.vanillagaming.org/?object=2857

Anhang:

Dies mag ein ehr geringer Fehler sein, jedoch sind Truhen eine gute Quelle um nebenbei etwas Gold zu machen, diese extrem erhöhten Timer machen das bereits schwere erlangen von Gold nochmal deutlich schwerer.

MfG, Queeb

**Comment by Elmo337** [comment]
Eine Quelle für die Respawns wäre ganz nett sonst machbar

**Comment by Queeb** [comment]
Ich hab mal Nostalrius angeguckt und wieso die deren Spawns hochgestellt haben und dort wurde es gemacht, da man mit den richtigen Spawnzeiten Kisten sehr leicht und schnell campen kann für etwa 6-8G pro stunde, somit easy 100G pro tag ohne wirkliche Arbeit/Gefahr.

Auch wenn die Spawnzeiten nicht Blizzlike sind, muss ich im nachhinein sagen, dass es eventuell so besser ist.

Ansonsten habe ich als einzige Quelle der Respawnzeiten: 
http://db.vanillagaming.org/?search=Solid+Chest

Die jeweiligen Chests haben aber je nach Position andere Zeiten, nicht nur nach ID. Ansonsten sind jedoch die dort angegebenen Spawnzeiten das, was wir vor dem Core change hatten.

(Auch wenn ich natürlich ebenfalls dieses easy Gold hätte, ist es vielleicht sinnvoller die Spawnzeiten hoch zu lassen. :p )

MfG, Queeb
