### ISSUE TITLE
Otho Moji'ko - Another Message to the Wildhammer

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#79]
**Name der Quest/Item/Object/etc**
Otho Moji'ko - Another Message to the Wildhammer
**Was Funktoniert nicht?**
Diese zweite Quest in der Quest Chain kann man zwar annehmen. Sie erscheint aber nicht im Questlog. Jetzt kann man bei Otho Moji'ko nur noch die Waren angucken. Quest abbrechen geht ebenfalls nicht, da nicht im Questlog. WDB Ordner löschen bringt nichts.
**Wie sollte es Funktonieren**
Man sollte die Quest ganz normal annehmen können, danach sollte sie im Questlog erscheinen.
(Dieser Bug wurde auch im Elysium Bugtracker reportet) https://elysium-project.org/bugtracker/issue/3637
**Screenshot/Video**

**Comment by Elmo337** [comment]
Fehler vermutlich gefunden , ist im nächsten Update drin

**Comment by Flaktrack** [comment]
Immer noch aktuell
