### ISSUE TITLE
[Azshara] Stealing Knowledge - Delivery to Andron Gant - Delivery to Magatha

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#80]
**Name der Quest/Item/Object/etc**
Stealing Knowledge - Delivery to Andron Gant - Delivery to Magatha
**Was Funktoniert nicht?**
Bei der Quest Stealing Knowledge [Questgeber: Jediga, Azshara 22.6, 51.4]  sind 2 Link-Quests buggy. Man muss zu 4 NPC's um die Tafeln abzugeben, davon geben Andron Gant [UC, 54.8, 76.3] und Magatha [TB, 44.0, 23.1] keine Folgequest. heißt: QUEST: Magatha's Payment to Jediga und QUEST: Andron's Payment to Jediga können nicht angenommen werden. Es kommt die Meldung: "Du erfüllst die Anforderung für diese Quest nicht".
**Wie sollte es Funktonieren**
QUEST: Magatha's Payment to Jediga und QUEST: Andron's Payment to Jediga sollten ganz normal angenommen werden, sowie es bei den anderen 2 von 4 Quests auch funktioniert. Bei unten stehendem Link ist nochmal alles verlinkt. 
**Screenshot/Video**
http://db.vanillagaming.org/?quest=3517

**Comment by Elmo337** [comment]
Ich kann alle annehmen

![Image of Yaktocat](http://i.epvpimg.com/gdiJbab.jpg)

**Comment by GitHubNoa** [comment]
ließ nochmal was ich geschrieben habe, es geht nicht um die Annahme der Quests in Azshara sondern um die Folgequests

**Comment by GitHubNoa** [comment]
'edit. Jetzt, 3 Leveln später kann ich die Quests annehmen, schau mal bitte nach [Andron's Payment to Jediga] und [Maghata's Payment to Jediga] welches Questleveln man braucht..das sollte nicht höher sein als das Level, was man zum annehmen der Ursprungsquest in Azshara rbaucht , die Level müssen alle gleich sein
