### ISSUE TITLE
Rethban Ore

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#81]
**Name der Quest/Item/Object/etc**
Rethban Ore
**Was Funktoniert nicht?**
In den Erzablagerungen im Redridge Gebirge befinden sich keine Rethban-Erze.
**Wie sollte es Funktonieren**
In den Erzablagerungen im Redridge Gebirge sollten sich von Zeit zu Zeit (ca. 33% Rate) Rethban-Erze befinden.
**Screenshot/Video**
Quelle: http://db.vanillagaming.org/?item=2798#mined-from-object

**Comment by Elmo337** [comment]
Hat bei uns eine 2% dropchance
