### ISSUE TITLE
Permanent -139 Rüstung

### ISSUE THREAD

**Issue by Tankman1** [Elmo337/Vanilla-WoW-Project#82]
Seit einem run Scholomance wird beim Rüstungswert im Charakter Fenster dauerhaft ein Abzug von -139 angezeigt. Auf dem Charakter selbst sind keine sichtbaren Debuffs oder ähnliches vorhanden.

Gruß

Tankman / Terra

**Comment by Tankman1** [comment]
Mittlerweile ist es wieder "verschwunden". Wenn wir das nächste mal scholo machen werde ich beobachten ob es erneut so ist.

**Comment by Elmo337** [comment]
Okay ich Close das dann
