### ISSUE TITLE
Quest Ascension und Blood of the Black Dragon Champion

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#84]
**Name der Quest/Item/Object/etc**
s.o.

**Was Funktoniert nicht?**
Hier wird immer vom NPC Rokaro gesprochen im Questtext...richtig wäre Rexxar...Rokaro kam später und ist dann auch stationär in Shadowprey Village

**Wie sollte es Funktonieren**
Text korrigieren

**Comment by GitHubNoa** [comment]
Rokaro ist aber im Spiel, der patroulliert vom Verbrannten Tal (Mündung Steinkrallengebirge) bis zu Shadowpray Village runter

**Comment by Nathaliana** [comment]
Das ist Rexxar
