### ISSUE TITLE
[QUEST]...and a Batch of Ooze

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#86]
**Name der Quest/Item/Object/etc**
...and a Batch of Ooze
**Was Funktoniert nicht?**
Laut Quest soll man Schleimproben in Un Goro sammeln. das Questitem was man für die Quest benötigt wird aber in Searing Gorge gedroppt von den Ogern [80.50]
In Un Goro droppt auch das Item was man später noch testen muss, in Searing Gorge droppt aber schon die fertige "Reine" Probe. Außerdem droppen die Schleimproben aus Un Goro immer noch mega schlecht, das sollte auf 85 % gefixxt sein? isses nicht, liegt bei geschätzten 30%
**Wie sollte es Funktonieren**
In Searing Gorge sollte das Item garnicht droppen.
**Screenshot/Video**

**Comment by Nathaliana** [comment]
Also a) Burning Steppe ist das und
b) nur die Firegut Brutes droppen das

**Comment by GitHubNoa** [comment]
jo haste recht
