### ISSUE TITLE
[QUEST] Mission: Possible but not probable [WICHTIG]

### ISSUE THREAD

**Issue by GitHubNoa** [Elmo337/Vanilla-WoW-Project#90]
**Name der Quest/Item/Object/etc**
Mission: Possible but not probable / KISTE Schloss knacken skillen
**Was Funktoniert nicht?**
Bei dieser Quest ist in der Kiste kein Gegenstand, stattdessen droppt der NPC vor der Truhe diesen. Eiegentlich skillen da Schurken Schlossknacken ab Skilllevel 101. Mit der Truhe kann man auch garnicht interagieren, sie ist kein Objekt in diesem Sinne. 
**Wie sollte es Funktonieren**
Besagte Truhe sollte ein Objekt sein und das Questitem [Cache of Zanzil's Altered Mixture] beinhalten.
**Screenshot/Video**
http://db.vanillagaming.org/?quest=2478

**Comment by Elmo337** [comment]
Funktioniert bei mir, ich kann das Object solange nicht  benutzen solange ich die Quest nicht hab. Außerdem dropt er das und die KIste dropt es
