### ISSUE TITLE
Freundliche Einheit ist aggressiv

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#94]
**Name der Quest/Item/Object/etc**
Gelkis Rumbler
**Was Funktoniert nicht?**
Obwohl ich bei den Gelkis Zentauren in Desolace bereits den Status "freundlich" erreicht habe, greifen mich die Minions (Erdelementare) der Gelkis Earthcaller, eben die bereits benannten Gelkis Rumbler, an sobald ich in Aggro Range bin.
**Wie sollte es Funktonieren**
Die Rumbler sollten genauso nicht-aggressiv sein wie der Rest der zur Gelkis-Fraktion gehörenden Mobs
**Screenshot/Video**
![image](https://user-images.githubusercontent.com/27807765/27923126-a28df50c-627d-11e7-8267-b45b299e44ba.png)

**Comment by Nathaliana** [comment]
Auch bei neutral wird man von denen angegriffen. Hab keine Quests für eine der beiden Seiten gemacht - einfach nur nach Feralas gelaufen. Beim Passieren vom Gelkis Village war ich dann neutral und wurde a) erst vom Rumbler angegriffen (der immer noch gelb war) und dann von so nem Gelkis Typen (wohl weil die beiden zusammenhängen).
