### ISSUE TITLE
Giftherstellung lernbar ohne Giftquest

### ISSUE THREAD

**Issue by Kampfkrapfn** [Elmo337/Vanilla-WoW-Project#95]
**Name der Quest/Item/Object/etc**
Mind-numbing Poison & Wound Poison
**Was Funktoniert nicht?**
Die Herstellung der beiden Gifte ist erlernbar, ohne vorher die Giftquest absolviert zu haben
**Wie sollte es Funktonieren**
Normalerweise sollte man erst die Level20-Giftquest machen und am Ende der Questreihe den Giftmisch-Skill bekommen, und dieser sollte Voraussetzung für alle Gifte sein.
**Screenshot/Video**

**Comment by Elmo337** [comment]
Bei meinem Allianz Schurke ging das nicht

**Comment by Kampfkrapfn** [comment]
ich behaupte, dass dies auch erst seit der Umstellung auf den Elysium Core so ist, und deinen Schurken hast du vorher schon gespielt afaik

**Comment by Elmo337** [comment]
Nein die Quest zu den Giften hab ich erst gemacht nachdem wir umgestiegen sind und ich hab mir auch auf dem GM Account 2 Schurken gemacht (Allianz und Horde) und den Fehler konnte ich nicht reproduzieren

**Comment by SailorSat** [comment]
Kann den Fehler bestätigen.
![wowscrnshot_102517_192751](https://user-images.githubusercontent.com/11991991/32074152-cafa3410-ba98-11e7-8c08-ac933a660347.jpg)
![wowscrnshot_102517_192758](https://user-images.githubusercontent.com/11991991/32074154-cb19a03e-ba98-11e7-9060-cb176da91e58.jpg)

Mind-numbing Poison (Rank 1) braucht "nur" Level 24, aber kein Giftmischen-Skill.
Wound Poison (Rank 1) braucht "nur" Level 32, aber kein Giftmischen-Skill.
