### ISSUE TITLE
Ashenvale Dark Strand Cultists

### ISSUE THREAD

**Issue by Nathaliana** [Elmo337/Vanilla-WoW-Project#98]
Deren Wichtel greifen nicht an, wenn man den "Beschwörer" angreift. Die Voids bei den Adepten hingegen funktionieren.

**Comment by Elmo337** [comment]
Wie heißen deren Wichtel?

**Comment by Nathaliana** [comment]
Hm sry keine Ahnung mehr - porte dich mal hin :)
